import 'dart:convert';
import '../../models/model_profile.dart';
import '../storage/app_database.dart';

class ModelCatalog {

  // ══════════════════════════════════════════════════════════════════════════
  // CLOUD MODELS  — API IDs verified June 2026
  // ══════════════════════════════════════════════════════════════════════════

  static const List<ModelProfile> cloudModels = [

    // ── OpenAI — GPT-5 Series (Current flagship as of June 2026) ─────────────
    ModelProfile(
      id: 'gpt-5.5',
      name: 'GPT-5.5',
      description: 'OpenAI current flagship — complex reasoning, coding, professional-grade tasks.',
      backend: ModelBackend.cloud,
      provider: 'openai',
      capabilities: [ModelCapability.chat, ModelCapability.vision, ModelCapability.code],
      tags: [ModelTag.newModel, ModelTag.powerful, ModelTag.reasoning, ModelTag.coding],
      apiModelId: 'gpt-5.5',
    ),
    ModelProfile(
      id: 'gpt-5.5-pro',
      name: 'GPT-5.5 Pro',
      description: 'OpenAI — high-precision variant of GPT-5.5 for maximum accuracy.',
      backend: ModelBackend.cloud,
      provider: 'openai',
      capabilities: [ModelCapability.chat, ModelCapability.vision, ModelCapability.code],
      tags: [ModelTag.newModel, ModelTag.powerful, ModelTag.reasoning],
      apiModelId: 'gpt-5.5-pro',
    ),
    ModelProfile(
      id: 'gpt-5.4',
      name: 'GPT-5.4',
      description: 'OpenAI affordable frontier — high-performance, cost-optimized coding & general tasks.',
      backend: ModelBackend.cloud,
      provider: 'openai',
      capabilities: [ModelCapability.chat, ModelCapability.vision, ModelCapability.code],
      tags: [ModelTag.newModel, ModelTag.popular, ModelTag.coding],
      apiModelId: 'gpt-5.4',
    ),
    ModelProfile(
      id: 'gpt-5.4-mini',
      name: 'GPT-5.4 Mini',
      description: 'OpenAI — strong, low-latency model ideal for coding subagents and high-volume apps.',
      backend: ModelBackend.cloud,
      provider: 'openai',
      capabilities: [ModelCapability.chat, ModelCapability.code],
      tags: [ModelTag.newModel, ModelTag.fast, ModelTag.coding, ModelTag.popular],
      apiModelId: 'gpt-5.4-mini',
    ),
    ModelProfile(
      id: 'gpt-5.4-nano',
      name: 'GPT-5.4 Nano',
      description: 'OpenAI — most cost-efficient reasoning model. Simple tasks at minimal cost.',
      backend: ModelBackend.cloud,
      provider: 'openai',
      capabilities: [ModelCapability.chat],
      tags: [ModelTag.newModel, ModelTag.fast],
      apiModelId: 'gpt-5.4-nano',
    ),
    ModelProfile(
      id: 'gpt-4.1',
      name: 'GPT-4.1',
      description: 'OpenAI GPT-4.1 — 1M context, superior instruction following. Still widely used.',
      backend: ModelBackend.cloud,
      provider: 'openai',
      capabilities: [ModelCapability.chat, ModelCapability.vision, ModelCapability.code],
      tags: [ModelTag.popular, ModelTag.coding, ModelTag.vision],
      apiModelId: 'gpt-4.1',
      contextLength: 1000000,
    ),
    ModelProfile(
      id: 'gpt-image-2',
      name: 'GPT Image 2',
      description: 'OpenAI — state-of-art cloud image generation model.',
      backend: ModelBackend.cloud,
      provider: 'openai',
      capabilities: [ModelCapability.imageGeneration],
      tags: [ModelTag.newModel, ModelTag.image, ModelTag.powerful],
      apiModelId: 'gpt-image-2',
    ),
    ModelProfile(
      id: 'gpt-realtime-2',
      name: 'GPT Realtime 2',
      description: 'OpenAI — low-latency voice & multimodal realtime interactions.',
      backend: ModelBackend.cloud,
      provider: 'openai',
      capabilities: [ModelCapability.voice, ModelCapability.chat],
      tags: [ModelTag.newModel, ModelTag.audio, ModelTag.fast],
      apiModelId: 'gpt-realtime-2',
    ),

    // ── Anthropic — Claude 4.x Series (Current as of June 2026) ──────────────
    ModelProfile(
      id: 'claude-opus-4-8',
      name: 'Claude Opus 4.8',
      description: 'Anthropic most capable — complex reasoning, agentic coding, 1M context.',
      backend: ModelBackend.cloud,
      provider: 'anthropic',
      capabilities: [ModelCapability.chat, ModelCapability.vision, ModelCapability.code],
      tags: [ModelTag.newModel, ModelTag.powerful, ModelTag.reasoning, ModelTag.coding],
      apiModelId: 'claude-opus-4-8',
      contextLength: 1000000,
    ),
    ModelProfile(
      id: 'claude-sonnet-4-6',
      name: 'Claude Sonnet 4.6',
      description: 'Anthropic — best intelligence + speed balance, 1M context. Most recommended.',
      backend: ModelBackend.cloud,
      provider: 'anthropic',
      capabilities: [ModelCapability.chat, ModelCapability.vision, ModelCapability.code],
      tags: [ModelTag.newModel, ModelTag.popular, ModelTag.fast, ModelTag.coding],
      apiModelId: 'claude-sonnet-4-6',
      contextLength: 1000000,
    ),
    ModelProfile(
      id: 'claude-haiku-4-5',
      name: 'Claude Haiku 4.5',
      description: 'Anthropic — fastest Claude with near-frontier intelligence. Lowest cost.',
      backend: ModelBackend.cloud,
      provider: 'anthropic',
      capabilities: [ModelCapability.chat],
      tags: [ModelTag.newModel, ModelTag.fast],
      apiModelId: 'claude-haiku-4-5-20251001',
    ),

    // ── Google — Gemini 3.x Series (Current as of June 2026) ─────────────────
    ModelProfile(
      id: 'gemini-3.5-flash',
      name: 'Gemini 3.5 Flash',
      description: 'Google latest flagship Flash — agentic tasks, coding, multimodal. High-performance.',
      backend: ModelBackend.cloud,
      provider: 'gemini',
      capabilities: [ModelCapability.chat, ModelCapability.vision, ModelCapability.code],
      tags: [ModelTag.newModel, ModelTag.fast, ModelTag.popular, ModelTag.reasoning],
      apiModelId: 'gemini-3.5-flash',
    ),
    ModelProfile(
      id: 'gemini-3.1-pro',
      name: 'Gemini 3.1 Pro',
      description: 'Google — high-end reasoning, complex multi-step workflows, sophisticated agentic AI.',
      backend: ModelBackend.cloud,
      provider: 'gemini',
      capabilities: [ModelCapability.chat, ModelCapability.vision, ModelCapability.code],
      tags: [ModelTag.newModel, ModelTag.powerful, ModelTag.reasoning, ModelTag.coding],
      apiModelId: 'gemini-3.1-pro-preview',
    ),
    ModelProfile(
      id: 'gemini-2.5-pro',
      name: 'Gemini 2.5 Pro',
      description: 'Google Gemini 2.5 Pro — stable, 1M context, production-ready. Still widely used.',
      backend: ModelBackend.cloud,
      provider: 'gemini',
      capabilities: [ModelCapability.chat, ModelCapability.vision, ModelCapability.code],
      tags: [ModelTag.popular, ModelTag.reasoning, ModelTag.coding],
      apiModelId: 'gemini-2.5-pro',
      contextLength: 1000000,
    ),
    ModelProfile(
      id: 'gemini-2.5-flash',
      name: 'Gemini 2.5 Flash',
      description: 'Google Gemini 2.5 Flash — fast & capable, adaptive thinking, best value.',
      backend: ModelBackend.cloud,
      provider: 'gemini',
      capabilities: [ModelCapability.chat, ModelCapability.vision],
      tags: [ModelTag.popular, ModelTag.fast, ModelTag.multilingual],
      apiModelId: 'gemini-2.5-flash-preview-05-20',
      contextLength: 1000000,
    ),

    // ── Mistral — Current Lineup (June 2026) ──────────────────────────────────
    ModelProfile(
      id: 'mistral-medium-3.5',
      name: 'Mistral Medium 3.5',
      description: 'Mistral frontier-class — multimodal, optimized for agentic & coding workflows.',
      backend: ModelBackend.cloud,
      provider: 'mistral',
      capabilities: [ModelCapability.chat, ModelCapability.vision, ModelCapability.code],
      tags: [ModelTag.newModel, ModelTag.powerful, ModelTag.coding, ModelTag.multilingual],
      apiModelId: 'mistral-medium-3.5-latest',
    ),
    ModelProfile(
      id: 'mistral-small-4',
      name: 'Mistral Small 4',
      description: 'Mistral — hybrid model unifying instruct, reasoning, and coding. Fast & efficient.',
      backend: ModelBackend.cloud,
      provider: 'mistral',
      capabilities: [ModelCapability.chat, ModelCapability.code],
      tags: [ModelTag.newModel, ModelTag.fast, ModelTag.multilingual],
      apiModelId: 'mistral-small-4-latest',
    ),
    ModelProfile(
      id: 'mistral-large-3',
      name: 'Mistral Large 3',
      description: 'Mistral — flagship open-weight, 128K context, general-purpose multimodal.',
      backend: ModelBackend.cloud,
      provider: 'mistral',
      capabilities: [ModelCapability.chat, ModelCapability.code],
      tags: [ModelTag.popular, ModelTag.powerful, ModelTag.multilingual],
      apiModelId: 'mistral-large-3-latest',
      contextLength: 128000,
    ),
    ModelProfile(
      id: 'devstral-2',
      name: 'Devstral 2',
      description: 'Mistral — frontier-level code agent for software engineering agentic tasks.',
      backend: ModelBackend.cloud,
      provider: 'mistral',
      capabilities: [ModelCapability.code, ModelCapability.chat],
      tags: [ModelTag.newModel, ModelTag.coding, ModelTag.powerful],
      apiModelId: 'devstral-latest',
    ),
    ModelProfile(
      id: 'codestral-latest',
      name: 'Codestral',
      description: 'Mistral — 256K code model, state-of-art code generation in 80+ languages.',
      backend: ModelBackend.cloud,
      provider: 'mistral',
      capabilities: [ModelCapability.code, ModelCapability.chat],
      tags: [ModelTag.coding, ModelTag.popular],
      apiModelId: 'codestral-latest',
      contextLength: 256000,
    ),

    // ── DeepSeek — V4 Series (Current as of June 2026) ────────────────────────
    ModelProfile(
      id: 'deepseek-v4-pro',
      name: 'DeepSeek V4 Pro',
      description: 'DeepSeek flagship — complex tasks, high-performance reasoning. Supports thinking mode.',
      backend: ModelBackend.cloud,
      provider: 'deepseek',
      capabilities: [ModelCapability.chat, ModelCapability.code],
      tags: [ModelTag.newModel, ModelTag.powerful, ModelTag.reasoning, ModelTag.coding],
      apiModelId: 'deepseek-v4-pro',
    ),
    ModelProfile(
      id: 'deepseek-v4-flash',
      name: 'DeepSeek V4 Flash',
      description: 'DeepSeek — high-efficiency, lower-latency. General-purpose at competitive cost.',
      backend: ModelBackend.cloud,
      provider: 'deepseek',
      capabilities: [ModelCapability.chat, ModelCapability.code],
      tags: [ModelTag.newModel, ModelTag.fast, ModelTag.popular, ModelTag.coding],
      apiModelId: 'deepseek-v4-flash',
    ),

    // ── Groq — Ultra-Fast Inference (June 2026) ───────────────────────────────
    ModelProfile(
      id: 'llama-4-scout-groq',
      name: 'Llama 4 Scout (Groq)',
      description: 'Meta Llama 4 Scout at Groq speed — 10M context, multimodal, ~800 t/s.',
      backend: ModelBackend.cloud,
      provider: 'groq',
      capabilities: [ModelCapability.chat, ModelCapability.vision, ModelCapability.code],
      tags: [ModelTag.newModel, ModelTag.fast, ModelTag.vision, ModelTag.popular],
      apiModelId: 'meta-llama/llama-4-scout-17b-16e-instruct',
      contextLength: 10000000,
    ),
    ModelProfile(
      id: 'llama-4-maverick-groq',
      name: 'Llama 4 Maverick (Groq)',
      description: 'Meta Llama 4 Maverick at Groq speed — 128K context, 400B total MoE params.',
      backend: ModelBackend.cloud,
      provider: 'groq',
      capabilities: [ModelCapability.chat, ModelCapability.vision, ModelCapability.code],
      tags: [ModelTag.newModel, ModelTag.fast, ModelTag.powerful, ModelTag.vision],
      apiModelId: 'meta-llama/llama-4-maverick-17b-128e-instruct',
      contextLength: 524288,
    ),
    ModelProfile(
      id: 'qwen3-32b-groq',
      name: 'Qwen3 32B (Groq)',
      description: 'Alibaba Qwen3 32B at Groq speed — hybrid thinking + non-thinking modes.',
      backend: ModelBackend.cloud,
      provider: 'groq',
      capabilities: [ModelCapability.chat, ModelCapability.code],
      tags: [ModelTag.newModel, ModelTag.fast, ModelTag.reasoning, ModelTag.multilingual],
      apiModelId: 'qwen/qwen3-32b',
    ),
    ModelProfile(
      id: 'whisper-groq',
      name: 'Whisper Large v3 (Groq)',
      description: 'Ultra-fast speech transcription — real-time multilingual STT via Groq.',
      backend: ModelBackend.cloud,
      provider: 'groq',
      capabilities: [ModelCapability.voice],
      tags: [ModelTag.fast, ModelTag.audio, ModelTag.multilingual],
      apiModelId: 'whisper-large-v3',
    ),

    // ── Together AI — Open-Weight at Scale ─────────────────────────────────────
    ModelProfile(
      id: 'llama-4-maverick-together',
      name: 'Llama 4 Maverick (Together)',
      description: 'Meta Llama 4 Maverick via Together AI — 400B MoE, multimodal, 524K context.',
      backend: ModelBackend.cloud,
      provider: 'together',
      capabilities: [ModelCapability.chat, ModelCapability.vision, ModelCapability.code],
      tags: [ModelTag.newModel, ModelTag.powerful, ModelTag.vision, ModelTag.multilingual],
      apiModelId: 'meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8',
      contextLength: 524288,
    ),
    ModelProfile(
      id: 'qwen3-235b-together',
      name: 'Qwen3 235B A22B (Together)',
      description: 'Alibaba Qwen3 MoE — 235B total, 22B active. Thinking + non-thinking mode.',
      backend: ModelBackend.cloud,
      provider: 'together',
      capabilities: [ModelCapability.chat, ModelCapability.code],
      tags: [ModelTag.newModel, ModelTag.powerful, ModelTag.reasoning, ModelTag.multilingual],
      apiModelId: 'Qwen/Qwen3-235B-A22B-fp8-tput',
    ),
  ];

  // ══════════════════════════════════════════════════════════════════════════
  // LOCAL MODELS  (GGUF — download & run on device)
  // ══════════════════════════════════════════════════════════════════════════

  static const List<ModelProfile> localModels = [

    // ── Qwen3 Series (2025 — Latest from Alibaba) ─────────────────────────────
    ModelProfile(
      id: 'qwen3-0.6b-local',
      name: 'Qwen3 0.6B',
      description: '🆕 Qwen3 nano — thinking + non-thinking modes. 600MB RAM. Best tiny model 2025.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat],
      tags: [ModelTag.newModel, ModelTag.tiny, ModelTag.fast, ModelTag.reasoning],
      ggufFilename: 'Qwen3-0.6B-Q4_K_M.gguf',
      downloadUrl: 'https://huggingface.co/unsloth/Qwen3-0.6B-GGUF/resolve/main/Qwen3-0.6B-Q4_K_M.gguf',
      fileSizeMb: 430,
      minRamMb: 768,
    ),
    ModelProfile(
      id: 'qwen3-1.7b-local',
      name: 'Qwen3 1.7B',
      description: '🆕 Qwen3 1.7B — hybrid thinking model. Beats many older 7B models.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat, ModelCapability.code],
      tags: [ModelTag.newModel, ModelTag.fast, ModelTag.reasoning, ModelTag.popular],
      ggufFilename: 'Qwen3-1.7B-Q4_K_M.gguf',
      downloadUrl: 'https://huggingface.co/unsloth/Qwen3-1.7B-GGUF/resolve/main/Qwen3-1.7B-Q4_K_M.gguf',
      fileSizeMb: 1100,
      minRamMb: 2048,
    ),
    ModelProfile(
      id: 'qwen3-4b-local',
      name: 'Qwen3 4B',
      description: '🆕 Qwen3 4B — reasoning powerhouse at 4B scale. Surpasses GPT-4o Mini.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat, ModelCapability.code],
      tags: [ModelTag.newModel, ModelTag.reasoning, ModelTag.powerful, ModelTag.popular],
      ggufFilename: 'Qwen3-4B-Q4_K_M.gguf',
      downloadUrl: 'https://huggingface.co/unsloth/Qwen3-4B-GGUF/resolve/main/Qwen3-4B-Q4_K_M.gguf',
      fileSizeMb: 2500,
      minRamMb: 4096,
    ),
    ModelProfile(
      id: 'qwen3-8b-local',
      name: 'Qwen3 8B',
      description: '🆕 Qwen3 8B — best 8B local model 2025. Deep reasoning, 128K context.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat, ModelCapability.code],
      tags: [ModelTag.newModel, ModelTag.reasoning, ModelTag.powerful, ModelTag.multilingual],
      ggufFilename: 'Qwen3-8B-Q4_K_M.gguf',
      downloadUrl: 'https://huggingface.co/unsloth/Qwen3-8B-GGUF/resolve/main/Qwen3-8B-Q4_K_M.gguf',
      fileSizeMb: 5200,
      minRamMb: 7168,
      contextLength: 131072,
    ),

    // ── Gemma 4 Series (2025 — Google's Latest) ───────────────────────────────
    ModelProfile(
      id: 'gemma4-1b-local',
      name: 'Gemma 4 1B',
      description: '🆕 Google Gemma 4 — 1B multimodal model. Vision + text, on-device Google quality.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat, ModelCapability.vision],
      tags: [ModelTag.newModel, ModelTag.tiny, ModelTag.fast, ModelTag.vision],
      ggufFilename: 'gemma-4-1b-it-Q4_K_M.gguf',
      downloadUrl: 'https://huggingface.co/bartowski/google_gemma-4-1b-it-GGUF/resolve/main/google_gemma-4-1b-it-Q4_K_M.gguf',
      fileSizeMb: 770,
      minRamMb: 1536,
    ),
    ModelProfile(
      id: 'gemma4-4b-local',
      name: 'Gemma 4 4B',
      description: '🆕 Google Gemma 4 4B — vision+text, 128K context, superb accuracy for size.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat, ModelCapability.vision],
      tags: [ModelTag.newModel, ModelTag.popular, ModelTag.vision, ModelTag.multilingual],
      ggufFilename: 'gemma-4-4b-it-Q4_K_M.gguf',
      downloadUrl: 'https://huggingface.co/bartowski/google_gemma-4-4b-it-GGUF/resolve/main/google_gemma-4-4b-it-Q4_K_M.gguf',
      fileSizeMb: 2700,
      minRamMb: 4096,
      contextLength: 131072,
    ),
    ModelProfile(
      id: 'gemma4-12b-local',
      name: 'Gemma 4 12B',
      description: '🆕 Gemma 4 12B — Google flagship local model. Vision+text, best Gemma yet.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat, ModelCapability.vision, ModelCapability.code],
      tags: [ModelTag.newModel, ModelTag.powerful, ModelTag.vision, ModelTag.reasoning],
      ggufFilename: 'gemma-4-12b-it-Q4_K_M.gguf',
      downloadUrl: 'https://huggingface.co/bartowski/google_gemma-4-12b-it-GGUF/resolve/main/google_gemma-4-12b-it-Q4_K_M.gguf',
      fileSizeMb: 7500,
      minRamMb: 10240,
      contextLength: 131072,
    ),

    // ── Llama 4 Series (2025 — Meta's Latest) ────────────────────────────────
    ModelProfile(
      id: 'llama-4-scout-local',
      name: 'Llama 4 Scout',
      description: '🆕 Meta Llama 4 Scout — 17B MoE, 10M context, multimodal. Meta\'s best local.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat, ModelCapability.vision, ModelCapability.code],
      tags: [ModelTag.newModel, ModelTag.powerful, ModelTag.vision, ModelTag.multilingual, ModelTag.popular],
      ggufFilename: 'Llama-4-Scout-17B-16E-Instruct-Q4_K_M.gguf',
      downloadUrl: 'https://huggingface.co/bartowski/Llama-4-Scout-17B-16E-Instruct-GGUF/resolve/main/Llama-4-Scout-17B-16E-Instruct-Q4_K_M.gguf',
      fileSizeMb: 10800,
      minRamMb: 14336,
      contextLength: 10000000,
    ),

    // ── Mistral 3 (2025) ──────────────────────────────────────────────────────
    ModelProfile(
      id: 'mistral-7b-v3-local',
      name: 'Mistral 7B v0.3',
      description: '🔥 Mistral 7B — fastest 7B model. Popular for creative writing and chat.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat, ModelCapability.code],
      tags: [ModelTag.popular, ModelTag.fast, ModelTag.multilingual],
      ggufFilename: 'Mistral-7B-Instruct-v0.3.Q4_K_M.gguf',
      downloadUrl: 'https://huggingface.co/bartowski/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3-Q4_K_M.gguf',
      fileSizeMb: 4400,
      minRamMb: 6144,
    ),

    // ── Phi-4 Series (2025 — Microsoft) ──────────────────────────────────────
    ModelProfile(
      id: 'phi-4-local',
      name: 'Phi-4 14B (Microsoft)',
      description: '🆕 Microsoft Phi-4 — 14B model outperforms 70B+ on math, science & reasoning.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat, ModelCapability.code],
      tags: [ModelTag.newModel, ModelTag.reasoning, ModelTag.powerful, ModelTag.coding],
      ggufFilename: 'phi-4-Q4_K_M.gguf',
      downloadUrl: 'https://huggingface.co/bartowski/phi-4-GGUF/resolve/main/phi-4-Q4_K_M.gguf',
      fileSizeMb: 8700,
      minRamMb: 10240,
    ),
    ModelProfile(
      id: 'phi-4-mini-local',
      name: 'Phi-4 Mini (Microsoft)',
      description: '🆕 Microsoft Phi-4 Mini — 3.8B reasoning model, mobile-friendly intelligence.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat, ModelCapability.code],
      tags: [ModelTag.newModel, ModelTag.fast, ModelTag.reasoning, ModelTag.tiny],
      ggufFilename: 'Phi-4-mini-instruct-Q4_K_M.gguf',
      downloadUrl: 'https://huggingface.co/bartowski/Phi-4-mini-instruct-GGUF/resolve/main/Phi-4-mini-instruct-Q4_K_M.gguf',
      fileSizeMb: 2400,
      minRamMb: 3072,
    ),

    // ── Qwen 2.5 (Still highly popular) ──────────────────────────────────────
    ModelProfile(
      id: 'qwen2.5-0.5b-local',
      name: 'Qwen 2.5 0.5B (Nano)',
      description: '🪶 Lightest local LLM. 395MB. Fits on any phone with 1GB RAM.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat],
      tags: [ModelTag.tiny, ModelTag.fast],
      ggufFilename: 'qwen2.5-0.5b-instruct-q4_k_m.gguf',
      downloadUrl: 'https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/qwen2.5-0.5b-instruct-q4_k_m.gguf',
      fileSizeMb: 395,
      minRamMb: 1024,
    ),
    ModelProfile(
      id: 'qwen2.5-3b-local',
      name: 'Qwen 2.5 3B',
      description: '⚡ Fast on-device chat. Great for 3GB+ RAM devices. Multilingual.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat, ModelCapability.code],
      tags: [ModelTag.fast, ModelTag.popular, ModelTag.multilingual],
      ggufFilename: 'qwen2.5-3b-instruct-q4_k_m.gguf',
      downloadUrl: 'https://huggingface.co/Qwen/Qwen2.5-3B-Instruct-GGUF/resolve/main/qwen2.5-3b-instruct-q4_k_m.gguf',
      fileSizeMb: 1900,
      minRamMb: 3072,
    ),
    ModelProfile(
      id: 'qwen2.5-7b-local',
      name: 'Qwen 2.5 7B',
      description: '💪 Near cloud quality. Best 7B multilingual model. Needs 6GB+ RAM.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat, ModelCapability.code],
      tags: [ModelTag.popular, ModelTag.powerful, ModelTag.multilingual],
      ggufFilename: 'qwen2.5-7b-instruct-q4_k_m.gguf',
      downloadUrl: 'https://huggingface.co/Qwen/Qwen2.5-7B-Instruct-GGUF/resolve/main/qwen2.5-7b-instruct-q4_k_m.gguf',
      fileSizeMb: 4700,
      minRamMb: 6144,
    ),

    // ── SmolLM2 (HuggingFace — ultra tiny) ───────────────────────────────────
    ModelProfile(
      id: 'smollm2-360m-local',
      name: 'SmolLM2 360M',
      description: '🤏 World\'s smallest capable LLM — 230MB, runs on 512MB RAM.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat],
      tags: [ModelTag.tiny, ModelTag.fast],
      ggufFilename: 'smollm2-360m-instruct-q4_k_m.gguf',
      downloadUrl: 'https://huggingface.co/HuggingFaceTB/SmolLM2-360M-Instruct-GGUF/resolve/main/smollm2-360m-instruct-q4_k_m.gguf',
      fileSizeMb: 230,
      minRamMb: 512,
    ),
    ModelProfile(
      id: 'smollm2-1.7b-local',
      name: 'SmolLM2 1.7B',
      description: '🤏 Small but mighty by HuggingFace. Great instruction following at 1GB size.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat],
      tags: [ModelTag.tiny, ModelTag.fast, ModelTag.popular],
      ggufFilename: 'smollm2-1.7b-instruct-q4_k_m.gguf',
      downloadUrl: 'https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct-GGUF/resolve/main/smollm2-1.7b-instruct-q4_k_m.gguf',
      fileSizeMb: 1060,
      minRamMb: 2048,
    ),

    // ── Code Specialist Models ────────────────────────────────────────────────
    ModelProfile(
      id: 'qwen2.5-coder-7b-local',
      name: 'Qwen 2.5 Coder 7B',
      description: '💻 #1 open-source code model at 7B. Beats GPT-4o on many code tasks.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.code, ModelCapability.chat],
      tags: [ModelTag.coding, ModelTag.powerful, ModelTag.popular],
      ggufFilename: 'qwen2.5-coder-7b-instruct-q4_k_m.gguf',
      downloadUrl: 'https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct-GGUF/resolve/main/qwen2.5-coder-7b-instruct-q4_k_m.gguf',
      fileSizeMb: 4700,
      minRamMb: 6144,
    ),
    ModelProfile(
      id: 'qwen2.5-coder-1.5b-local',
      name: 'Qwen 2.5 Coder 1.5B',
      description: '💻 Lightweight code assistant. 92 languages. Offline IDE companion.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.code, ModelCapability.chat],
      tags: [ModelTag.coding, ModelTag.fast, ModelTag.tiny],
      ggufFilename: 'qwen2.5-coder-1.5b-instruct-q4_k_m.gguf',
      downloadUrl: 'https://huggingface.co/Qwen/Qwen2.5-Coder-1.5B-Instruct-GGUF/resolve/main/qwen2.5-coder-1.5b-instruct-q4_k_m.gguf',
      fileSizeMb: 986,
      minRamMb: 2048,
    ),
    ModelProfile(
      id: 'deepseek-r1-14b-local',
      name: 'DeepSeek R1 14B (Reasoning)',
      description: '🧠 DeepSeek R1 distilled to 14B — reasoning with visible thinking process.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat, ModelCapability.code],
      tags: [ModelTag.reasoning, ModelTag.powerful, ModelTag.coding, ModelTag.popular],
      ggufFilename: 'DeepSeek-R1-Distill-Qwen-14B-Q4_K_M.gguf',
      downloadUrl: 'https://huggingface.co/bartowski/DeepSeek-R1-Distill-Qwen-14B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-14B-Q4_K_M.gguf',
      fileSizeMb: 8900,
      minRamMb: 10240,
    ),
    ModelProfile(
      id: 'deepseek-r1-7b-local',
      name: 'DeepSeek R1 7B (Reasoning)',
      description: '🧠 DeepSeek R1 7B — chain-of-thought reasoning for mid-range devices.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat, ModelCapability.code],
      tags: [ModelTag.reasoning, ModelTag.coding, ModelTag.newModel],
      ggufFilename: 'DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf',
      downloadUrl: 'https://huggingface.co/bartowski/DeepSeek-R1-Distill-Qwen-7B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf',
      fileSizeMb: 4700,
      minRamMb: 6144,
    ),

    // ── 🔓 UNCENSORED MODELS ──────────────────────────────────────────────────
    // No safety filters applied — for research & unrestricted use.
    ModelProfile(
      id: 'dolphin-2.9-llama3-8b-local',
      name: 'Dolphin 3.0 Llama 3.1 8B 🔓',
      description: '🔓 Dolphin — fine-tuned Llama 3.1, no RLHF restrictions. Helpful, honest, uncensored assistant.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat, ModelCapability.code],
      tags: [ModelTag.uncensored, ModelTag.popular, ModelTag.roleplay],
      ggufFilename: 'dolphin-3.0-llama3.1-8b-Q4_K_M.gguf',
      downloadUrl: 'https://huggingface.co/bartowski/dolphin-3.0-llama3.1-8b-GGUF/resolve/main/dolphin-3.0-llama3.1-8b-Q4_K_M.gguf',
      fileSizeMb: 4900,
      minRamMb: 6144,
    ),
    ModelProfile(
      id: 'dolphin-mistral-7b-local',
      name: 'Dolphin 2.9 Mistral 7B 🔓',
      description: '🔓 Uncensored Mistral — DPO fine-tuned, no content restrictions. Research & roleplay.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat],
      tags: [ModelTag.uncensored, ModelTag.fast, ModelTag.roleplay],
      ggufFilename: 'dolphin-2.9.2-mistral-7b-v0.1-Q4_K_M.gguf',
      downloadUrl: 'https://huggingface.co/bartowski/dolphin-2.9.2-mistral-7b-v0.1-GGUF/resolve/main/dolphin-2.9.2-mistral-7b-v0.1-Q4_K_M.gguf',
      fileSizeMb: 4400,
      minRamMb: 6144,
    ),
    ModelProfile(
      id: 'wizardlm2-7b-local',
      name: 'WizardLM-2 7B 🔓',
      description: '🔓 WizardLM-2 uncensored — Microsoft research model, strong reasoning & roleplay.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat, ModelCapability.code],
      tags: [ModelTag.uncensored, ModelTag.powerful, ModelTag.roleplay, ModelTag.reasoning],
      ggufFilename: 'WizardLM-2-7B.Q4_K_M.gguf',
      downloadUrl: 'https://huggingface.co/bartowski/WizardLM-2-7B-GGUF/resolve/main/WizardLM-2-7B-Q4_K_M.gguf',
      fileSizeMb: 4400,
      minRamMb: 6144,
    ),
    ModelProfile(
      id: 'llama3-8b-lexi-uncensored-local',
      name: 'Llama 3 Lexi 8B 🔓',
      description: '🔓 Llama 3 fully uncensored via Orion fine-tune. No guardrails, unrestricted creative use.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat],
      tags: [ModelTag.uncensored, ModelTag.roleplay, ModelTag.newModel],
      ggufFilename: 'Llama-3-8B-Lexi-Uncensored-V2-Q4_K_M.gguf',
      downloadUrl: 'https://huggingface.co/bartowski/Llama-3-8B-Lexi-Uncensored-V2-GGUF/resolve/main/Llama-3-8B-Lexi-Uncensored-V2-Q4_K_M.gguf',
      fileSizeMb: 4900,
      minRamMb: 6144,
    ),
    ModelProfile(
      id: 'qwen2.5-uncensored-7b-local',
      name: 'Qwen 2.5 7B Uncensored 🔓',
      description: '🔓 Qwen 2.5 7B with abliterated safety filters — multilingual unrestricted responses.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat, ModelCapability.code],
      tags: [ModelTag.uncensored, ModelTag.multilingual, ModelTag.roleplay],
      ggufFilename: 'Qwen2.5-7B-Instruct-abliterated-Q4_K_M.gguf',
      downloadUrl: 'https://huggingface.co/bartowski/Qwen2.5-7B-Instruct-abliterated-GGUF/resolve/main/Qwen2.5-7B-Instruct-abliterated-Q4_K_M.gguf',
      fileSizeMb: 4700,
      minRamMb: 6144,
    ),

    // ── Vision / Multimodal ───────────────────────────────────────────────────
    ModelProfile(
      id: 'minicpm-v-2.6-local',
      name: 'MiniCPM-V 2.6',
      description: '👁️ On-device vision + text. Describe images, read charts, analyze photos offline.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat, ModelCapability.vision],
      tags: [ModelTag.vision, ModelTag.popular],
      ggufFilename: 'MiniCPM-V-2_6-Q4_K_M.gguf',
      downloadUrl: 'https://huggingface.co/openbmb/MiniCPM-V-2_6-gguf/resolve/main/MiniCPM-V-2_6-Q4_K_M.gguf',
      fileSizeMb: 5200,
      minRamMb: 6144,
    ),
    ModelProfile(
      id: 'llava-llama3-8b-local',
      name: 'LLaVA 1.6 Llama 3 8B (Vision)',
      description: '👁️ Powerful visual understanding — analyze images with Llama 3 backbone.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat, ModelCapability.vision],
      tags: [ModelTag.vision, ModelTag.powerful],
      ggufFilename: 'llava-llama-3-8b-v1_1-int4.gguf',
      downloadUrl: 'https://huggingface.co/xtuner/llava-llama-3-8b-v1_1-gguf/resolve/main/llava-llama-3-8b-v1_1-int4.gguf',
      fileSizeMb: 5100,
      minRamMb: 7168,
    ),
    ModelProfile(
      id: 'moondream2-local',
      name: 'Moondream 2 (Tiny Vision)',
      description: '🌙 2B vision model — fast image understanding. Ideal for low-end devices.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.vision, ModelCapability.chat],
      tags: [ModelTag.vision, ModelTag.tiny, ModelTag.fast],
      ggufFilename: 'moondream2-text-model-f16.gguf',
      downloadUrl: 'https://huggingface.co/vikhyatk/moondream2/resolve/main/moondream2-text-model-f16.gguf',
      fileSizeMb: 3400,
      minRamMb: 4096,
    ),

    // ── Roleplay / Creative Models ─────────────────────────────────────────────
    ModelProfile(
      id: 'hermes3-llama3.1-8b-local',
      name: 'Hermes 3 Llama 3.1 8B',
      description: '🎭 Hermes 3 — best roleplay + instruction model. Long context creative writing.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat],
      tags: [ModelTag.roleplay, ModelTag.popular, ModelTag.powerful],
      ggufFilename: 'Hermes-3-Llama-3.1-8B.Q4_K_M.gguf',
      downloadUrl: 'https://huggingface.co/bartowski/Hermes-3-Llama-3.1-8B-GGUF/resolve/main/Hermes-3-Llama-3.1-8B.Q4_K_M.gguf',
      fileSizeMb: 4900,
      minRamMb: 6144,
    ),
    ModelProfile(
      id: 'mythomax-l2-13b-local',
      name: 'MythoMax L2 13B',
      description: '🎭 MythoMax — community favorite for storytelling, roleplay and creative fiction.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.chat],
      tags: [ModelTag.roleplay, ModelTag.popular, ModelTag.uncensored],
      ggufFilename: 'MythoMax-L2-13b.Q4_K_M.gguf',
      downloadUrl: 'https://huggingface.co/TheBloke/MythoMax-L2-13B-GGUF/resolve/main/MythoMax-L2-13b.Q4_K_M.gguf',
      fileSizeMb: 7900,
      minRamMb: 10240,
    ),

    // ── Voice / Whisper STT ───────────────────────────────────────────────────
    ModelProfile(
      id: 'whisper-tiny-local',
      name: 'Whisper Tiny',
      description: '🎤 OpenAI Whisper — 75MB, English optimized. Instant transcription.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.voice],
      tags: [ModelTag.audio, ModelTag.tiny, ModelTag.fast],
      ggufFilename: 'ggml-tiny.en.bin',
      downloadUrl: 'https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-tiny.en.bin',
      fileSizeMb: 75,
      minRamMb: 512,
    ),
    ModelProfile(
      id: 'whisper-base-local',
      name: 'Whisper Base (Multilingual)',
      description: '🎤 Whisper Base — 99 languages, great accuracy at 142MB.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.voice],
      tags: [ModelTag.audio, ModelTag.fast, ModelTag.multilingual],
      ggufFilename: 'ggml-base.bin',
      downloadUrl: 'https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.bin',
      fileSizeMb: 142,
      minRamMb: 512,
    ),
    ModelProfile(
      id: 'whisper-small-local',
      name: 'Whisper Small',
      description: '🎤 Whisper Small — best balance of accuracy and speed for STT.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.voice],
      tags: [ModelTag.audio, ModelTag.multilingual, ModelTag.popular],
      ggufFilename: 'ggml-small.bin',
      downloadUrl: 'https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-small.bin',
      fileSizeMb: 466,
      minRamMb: 1024,
    ),
    ModelProfile(
      id: 'whisper-medium-local',
      name: 'Whisper Medium',
      description: '🎤 Whisper Medium — near-perfect transcription for 99 languages. 1.5GB.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.voice],
      tags: [ModelTag.audio, ModelTag.multilingual, ModelTag.powerful],
      ggufFilename: 'ggml-medium.bin',
      downloadUrl: 'https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-medium.bin',
      fileSizeMb: 1530,
      minRamMb: 2048,
    ),
    ModelProfile(
      id: 'supertonic-3-local',
      name: 'Supertonic 3',
      description: '🎤 Supertonic 3 — high-performance on-device voice generation (TTS). Supporting 31 languages and expressive styling.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.voice],
      tags: [ModelTag.audio, ModelTag.newModel, ModelTag.fast, ModelTag.multilingual],
      ggufFilename: 'supertonic-3.onnx',
      downloadUrl: 'https://huggingface.co/Supertone/supertonic-3/resolve/main/supertonic-3.onnx',
      fileSizeMb: 198,
      minRamMb: 1024,
    ),
    ModelProfile(
      id: 'kokoro-82m-local',
      name: 'Kokoro 82M v1.0',
      description: '🎤 SOTA 82M parameter text-to-speech engine. Incredible voice quality and expression at only 82M parameters.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.voice],
      tags: [ModelTag.audio, ModelTag.newModel, ModelTag.fast, ModelTag.tiny],
      ggufFilename: 'kokoro-82m-v1.0.onnx',
      downloadUrl: 'https://huggingface.co/onnx-community/Kokoro-82M-v1.0-ONNX/resolve/main/onnx/model.onnx',
      fileSizeMb: 340,
      minRamMb: 512,
    ),
    ModelProfile(
      id: 'bark-small-local',
      name: 'Bark Small',
      description: '🎤 Suno Bark Small — transformer-based audio synthesis (TTS). Generates realistic speech, music, and background noise.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.voice],
      tags: [ModelTag.audio, ModelTag.popular],
      ggufFilename: 'pytorch_model.bin',
      downloadUrl: 'https://huggingface.co/suno/bark-small/resolve/main/pytorch_model.bin',
      fileSizeMb: 500,
      minRamMb: 2048,
    ),


    // ── Image Generation ──────────────────────────────────────────────────────
    ModelProfile(
      id: 'flux-schnell-local',
      name: 'FLUX.1 Schnell',
      description: '🎨 FLUX.1 — state-of-art photorealistic image gen. Black Forest Labs. 6.7GB.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.imageGeneration],
      tags: [ModelTag.image, ModelTag.powerful, ModelTag.popular, ModelTag.newModel],
      ggufFilename: 'flux1-schnell-q4_k_m.gguf',
      downloadUrl: 'https://huggingface.co/city96/FLUX.1-schnell-gguf/resolve/main/flux1-schnell-q4_k_m.gguf',
      fileSizeMb: 6700,
      minRamMb: 10240,
    ),
    ModelProfile(
      id: 'flux-dev-local',
      name: 'FLUX.1 Dev',
      description: '🎨 FLUX.1 Dev — higher quality than Schnell for non-commercial local art. 12 steps.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.imageGeneration],
      tags: [ModelTag.image, ModelTag.powerful, ModelTag.newModel],
      ggufFilename: 'flux1-dev-Q4_K_M.gguf',
      downloadUrl: 'https://huggingface.co/city96/FLUX.1-dev-gguf/resolve/main/flux1-dev-Q4_K_M.gguf',
      fileSizeMb: 6900,
      minRamMb: 10240,
    ),
    ModelProfile(
      id: 'sdxl-turbo-local',
      name: 'SDXL-Turbo',
      description: '🎨 SDXL-Turbo — real-time 1024×1024 generation in just 1–4 steps. 6.5GB.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.imageGeneration],
      tags: [ModelTag.image, ModelTag.fast, ModelTag.popular],
      ggufFilename: 'sd_xl_turbo_1.0_fp16.gguf',
      downloadUrl: 'https://huggingface.co/second-state/SDXL-Turbo-GGUF/resolve/main/sd_xl_turbo_1.0_fp16.gguf',
      fileSizeMb: 6500,
      minRamMb: 8192,
    ),
    ModelProfile(
      id: 'sd-v1.5-local',
      name: 'Stable Diffusion 1.5',
      description: '🎨 Classic SD 1.5 — reliable image generation with massive community support.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.imageGeneration],
      tags: [ModelTag.image, ModelTag.popular],
      ggufFilename: 'v1-5-pruned-emaonly.gguf',
      downloadUrl: 'https://huggingface.co/second-state/stable-diffusion-v1-5-GGUF/resolve/main/v1-5-pruned-emaonly.gguf',
      fileSizeMb: 2050,
      minRamMb: 4096,
    ),
    ModelProfile(
      id: 'tiny-sd-local',
      name: 'Tiny Stable Diffusion',
      description: '🎨 Ultra-light SD — 180MB, offline art generation on any device instantly.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.imageGeneration],
      tags: [ModelTag.image, ModelTag.tiny, ModelTag.fast],
      ggufFilename: 'tiny-sd-q4_k_m.gguf',
      downloadUrl: 'https://huggingface.co/Oobleck/tiny-sd-gguf/resolve/main/tiny-sd-q4_k_m.gguf',
      fileSizeMb: 180,
      minRamMb: 2048,
    ),

    // ── Text Embeddings ───────────────────────────────────────────────────────
    ModelProfile(
      id: 'nomic-embed-local',
      name: 'Nomic Embed Text v1.5',
      description: '📊 High-quality text embeddings for local RAG, search, and semantic similarity.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.embedding],
      tags: [ModelTag.embedding, ModelTag.popular, ModelTag.fast],
      ggufFilename: 'nomic-embed-text-v1.5.Q4_K_M.gguf',
      downloadUrl: 'https://huggingface.co/nomic-ai/nomic-embed-text-v1.5-GGUF/resolve/main/nomic-embed-text-v1.5.Q4_K_M.gguf',
      fileSizeMb: 84,
      minRamMb: 512,
    ),
    ModelProfile(
      id: 'all-minilm-embed-local',
      name: 'All-MiniLM-L6 Embed',
      description: '📊 Sentence Transformers — ultra-fast semantic embeddings, only 22MB.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.embedding],
      tags: [ModelTag.embedding, ModelTag.tiny, ModelTag.fast],
      ggufFilename: 'all-MiniLM-L6-v2-Q4_K_M.gguf',
      downloadUrl: 'https://huggingface.co/second-state/All-MiniLM-L6-v2-Embedding-GGUF/resolve/main/all-MiniLM-L6-v2-Q4_K_M.gguf',
      fileSizeMb: 22,
      minRamMb: 256,
    ),
    ModelProfile(
      id: 'mxbai-embed-large-local',
      name: 'mxbai-embed-large-v1',
      description: '📊 MixedBread embed-large — outperforms OpenAI ada-002 on MTEB. 669MB.',
      backend: ModelBackend.local,
      provider: 'local',
      capabilities: [ModelCapability.embedding],
      tags: [ModelTag.embedding, ModelTag.powerful, ModelTag.newModel],
      ggufFilename: 'mxbai-embed-large-v1-Q4_K_M.gguf',
      downloadUrl: 'https://huggingface.co/ChristianAzinn/mxbai-embed-large-v1-gguf/resolve/main/mxbai-embed-large-v1-Q4_K_M.gguf',
      fileSizeMb: 669,
      minRamMb: 1024,
    ),
  ];

  static List<ModelProfile> getCustomModels() {
    try {
      final items = AppDatabase.instance.getMemories(type: 'custom_model_profile', limit: 100);
      return items.map((item) {
        final contentMap = jsonDecode(item['content'] as String) as Map<String, dynamic>;
        return ModelProfile.fromJson(contentMap);
      }).toList();
    } catch (_) {
      return [];
    }
  }

  static List<ModelProfile> get allModels => [
        ...cloudModels,
        ...localModels,
        ...getCustomModels(),
      ];

  static ModelProfile? findById(String id) {
    try {
      return allModels.firstWhere((m) => m.id == id);
    } catch (_) {
      return null;
    }
  }

  /// Filter local models by capability category (includes custom models).
  static List<ModelProfile> localByCapability(ModelCapability cap) {
    return [...localModels, ...getCustomModels()]
        .where((m) => m.capabilities.contains(cap))
        .toList();
  }

  /// Filter local models by tag.
  static List<ModelProfile> localByTag(ModelTag tag) {
    return [...localModels, ...getCustomModels()]
        .where((m) => m.tags.contains(tag))
        .toList();
  }
}
